### ISSUE TITLE
Cannot run the project directly after cloning it 

### ISSUE THREAD

**Issue by sunnynagavo** [foxminchan/BookWorm#1]
I tried to git clone it and then tried running the project with dotnet run command and this is what I am seeing. 

let me look into the code but the read me file needs to be updated 

![image](https://github.com/user-attachments/assets/ce211141-a3e6-4ab3-b027-be25e2f99bbc)

**Comment by Gio2k** [comment]
You can fix that by adding the missing parameters to e.g. the Development appsettings:
`
  "Parameters": {
    "SqlUser": "admin",
    "SqlPassword": "somepassword"
  }
`

However, once you fix the first issue, the next one waits over the corner.

**Comment by sunnynagavo** [comment]
> You can fix that by adding the missing parameters to e.g. the Development appsettings: `"Parameters": { "SqlUser": "admin", "SqlPassword": "somepassword" }`
> 


Ok thank you, can we just add this parameters in the apphost appsettings.json file inside repo, so that no one has to go through the pain of figuring it out what went wrong.

> However, once you fix the first issue, the next one waits over the corner.
what other errors are you seeing ?

**Comment by sunnynagavo** [comment]
ok one more I am seeing 

![image](https://github.com/user-attachments/assets/de2b42fb-0565-4d0d-90e1-edb249c34f76)

**Comment by sunnynagavo** [comment]
some services are not able to be constructed 

![image](https://github.com/user-attachments/assets/2f0bb2e7-476a-4ad1-8ee0-31c1fd3c44c2)

**Comment by sunnynagavo** [comment]
from Aspire dashboard 

![image](https://github.com/user-attachments/assets/d837feaf-473f-421b-a76c-775df23f6476)

**Comment by foxminchan** [comment]
@sunnynagavo I have just updated the README to configure user-secret for parameters and connection strings. Additionally, I have also fixed issues related to MongoDB service registration. Due to needing to complete project tasks at the company, I only now had the time to fix these issues.
